# Generated by Django 3.2.9 on 2021-11-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_registered_dday', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
