# Generated by Django 3.2.9 on 2021-11-29 15:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211115_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(default='', upload_to=accounts.models.user_profilepic_path),
        ),
    ]
