# Generated by Django 3.2.9 on 2021-12-02 09:26

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, default='', upload_to=accounts.models.user_profilepic_path),
        ),
    ]
