# Generated by Django 3.2.9 on 2022-03-01 10:13

from django.db import migrations, models
import django.db.models.deletion
import timetable_v2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0024_classtingurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimetableMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom', verbose_name='시간표를 만들 교실을 선택하세요.')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='시정표 이름')),
                ('startdate', models.DateField(verbose_name='시정표 적용 시작 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='시정표 항목 이름')),
                ('start_time', models.TimeField(verbose_name='시정표 항목 시작 시간')),
                ('end_time', models.TimeField(verbose_name='시정표 항목 종료 시간')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='StaticClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='수업 이름')),
                ('short_name', models.CharField(max_length=3, verbose_name='축약 이름')),
                ('location', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='수업 교실')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher', verbose_name='담당 교사')),
            ],
        ),
        migrations.CreateModel(
            name='FlexibleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='수업 이름')),
                ('short_name', models.CharField(max_length=3, verbose_name='축약 이름')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='수업 교실')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher', verbose_name='담당 교사')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTimetableTempItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('time', models.IntegerField(verbose_name='교시')),
                ('class_temp_custom_name', models.CharField(blank=True, max_length=12, null=True, verbose_name='사용자 지정 임시 수업 이름')),
                ('class_temp_custom_short_name', models.CharField(blank=True, max_length=3, null=True, verbose_name='사용자 지정 임시 수업 축약 이름')),
                ('class_temp_custom_place', models.CharField(blank=True, max_length=20, null=True)),
                ('class_flexible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.flexibleclass', verbose_name='수업')),
                ('class_static', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.staticclass', verbose_name='수업')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.classtimetablemaster', verbose_name='시간표')),
            ],
            options={
                'unique_together': {('timetable', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='ClassTimetableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', timetable_v2.models.DayOfTheWeekField(choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (7, '일요일')], verbose_name='요일')),
                ('time', models.IntegerField(verbose_name='교시')),
                ('class_flexible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.flexibleclass', verbose_name='수업')),
                ('class_static', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.staticclass', verbose_name='수업')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.classtimetablemaster', verbose_name='시간표')),
            ],
            options={
                'unique_together': {('timetable', 'day_of_week')},
            },
        ),
    ]
