# Generated by Django 3.2.9 on 2022-03-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_classtingurl'),
        ('timetable_v2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='수업 이름')),
                ('short_name', models.CharField(max_length=4, verbose_name='수업 축약 이름')),
                ('location_etc', models.CharField(blank=True, max_length=30, null=True, verbose_name='수업 교실 (기타 경우)')),
                ('time', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='타임')),
                ('location_classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='수업 교실')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher', verbose_name='담당 교사')),
            ],
            options={
                'unique_together': {('name', 'time')},
            },
        ),
        migrations.RemoveField(
            model_name='classtimetableitem',
            name='class_flexible',
        ),
        migrations.RemoveField(
            model_name='classtimetabletempitem',
            name='class_flexible',
        ),
        migrations.RemoveField(
            model_name='staticclass',
            name='location',
        ),
        migrations.AddField(
            model_name='classtimetableitem',
            name='type',
            field=models.CharField(choices=[('STATIC', '반 단위 수업'), ('FLEXIBLE', '이동 수업'), ('TIME', '타임형 수업')], default='STATIC', max_length=8, verbose_name='수업 형식'),
        ),
        migrations.AddField(
            model_name='staticclass',
            name='location_classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='수업 교실'),
        ),
        migrations.AddField(
            model_name='staticclass',
            name='location_etc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='수업 교실 (기타 경우)'),
        ),
        migrations.AlterField(
            model_name='classtimetableitem',
            name='class_static',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.staticclass', verbose_name='반단위 수업'),
        ),
        migrations.AlterField(
            model_name='classtimetabletempitem',
            name='class_static',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.staticclass', verbose_name='반단위 수업'),
        ),
        migrations.AlterField(
            model_name='staticclass',
            name='short_name',
            field=models.CharField(max_length=4, verbose_name='수업 축약 이름'),
        ),
        migrations.DeleteModel(
            name='FlexibleClass',
        ),
        migrations.AddField(
            model_name='classtimetableitem',
            name='class_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.timeclass', verbose_name='타임형 수업'),
        ),
        migrations.AddField(
            model_name='classtimetabletempitem',
            name='class_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.timeclass', verbose_name='타임형 수업'),
        ),
    ]
