# Generated by Django 3.2.9 on 2022-03-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_classtingurl'),
        ('timetable_v2', '0002_auto_20220303_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticclass',
            name='location_classroom',
        ),
        migrations.RemoveField(
            model_name='staticclass',
            name='location_etc',
        ),
        migrations.RemoveField(
            model_name='timeclass',
            name='location_classroom',
        ),
        migrations.RemoveField(
            model_name='timeclass',
            name='location_etc',
        ),
        migrations.AlterField(
            model_name='classtimetableitem',
            name='class_static',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.staticclass', verbose_name='반 단위 수업'),
        ),
        migrations.CreateModel(
            name='FlexibleClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True, verbose_name='수업 이름')),
                ('short_name', models.CharField(max_length=4, verbose_name='수업 축약 이름')),
                ('location_etc', models.CharField(blank=True, max_length=30, null=True, verbose_name='수업 교실 (기타 경우)')),
                ('location_classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='수업 교실')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher', verbose_name='담당 교사')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classtimetableitem',
            name='class_flexible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.flexibleclass', verbose_name='이동 수업'),
        ),
        migrations.AddField(
            model_name='classtimetabletempitem',
            name='class_flexible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.flexibleclass', verbose_name='이동 수업'),
        ),
    ]
