# Generated by Django 3.2.9 on 2022-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_classtingurl'),
        ('timetable_v2', '0003_auto_20220303_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexibleclass',
            name='name',
            field=models.CharField(max_length=12, verbose_name='수업 이름'),
        ),
        migrations.AlterUniqueTogether(
            name='flexibleclass',
            unique_together={('name', 'location_classroom', 'location_etc')},
        ),
    ]
