# Generated by Django 3.2.9 on 2022-03-03 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0024_classtingurl'),
        ('timetable_v2', '0004_auto_20220303_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeclass',
            name='location_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='수업 교실'),
        ),
        migrations.AddField(
            model_name='timeclass',
            name='location_etc',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='수업 교실 (기타 경우)'),
        ),
        migrations.AlterField(
            model_name='flexibleclass',
            name='location_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom', verbose_name='수업 교실'),
        ),
        migrations.AlterUniqueTogether(
            name='timeclass',
            unique_together={('name', 'time', 'location_classroom', 'location_etc')},
        ),
    ]
