# Generated by Django 3.2.9 on 2022-03-03 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_v2', '0005_auto_20220303_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='startdate',
        ),
        migrations.CreateModel(
            name='TimeTableWithDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(verbose_name='시정표 적용 시작 날짜')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable_v2.timetable')),
            ],
        ),
    ]
