# Generated by Django 3.2.9 on 2022-03-04 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_v2', '0007_auto_20220303_2236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classtimetableitem',
            unique_together={('timetable', 'day_of_week', 'time')},
        ),
    ]
