# Generated by Django 3.2.9 on 2022-03-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_v2', '0008_alter_classtimetableitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code_hex', models.CharField(max_length=7, verbose_name='색상 코드')),
                ('name', models.CharField(max_length=36, verbose_name='색상 이름')),
            ],
        ),
    ]
