# Generated by Django 3.2.9 on 2022-03-05 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_v2', '0010_rename_color_code_hex_color_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibleclass',
            name='color',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable_v2.color', verbose_name='수업 색상'),
        ),
        migrations.AddField(
            model_name='staticclass',
            name='color',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable_v2.color', verbose_name='수업 색상'),
        ),
        migrations.AddField(
            model_name='timeclass',
            name='color',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable_v2.color', verbose_name='수업 색상'),
        ),
    ]
