# Generated by Django 3.2.9 on 2022-03-09 03:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable_v2', '0011_auto_20220305_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userclasstimetableitem',
            unique_together={('user', 'day_of_week', 'time')},
        ),
        migrations.RemoveField(
            model_name='userclasstimetableitem',
            name='timetable',
        ),
    ]
