# Generated by Django 3.2.9 on 2022-04-05 14:08

from django.db import migrations, models
import timetable_v2.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable_v2', '0013_auto_20220310_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaySwapAll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('target_day', timetable_v2.models.DayOfTheWeekField(choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (7, '일요일')], verbose_name='요일')),
            ],
            options={
                'unique_together': {('date', 'target_day')},
            },
        ),
    ]
