# Generated by Django 3.2.9 on 2021-11-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.IntegerField(choices=[(1, '조식'), (2, '중식'), (3, '석식')], default=2, verbose_name='식사명')),
                ('number_of_people', models.IntegerField(verbose_name='급식인원수')),
                ('calories', models.IntegerField(verbose_name='칼로리')),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('allergy_codes', models.CharField(blank=True, max_length=30)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_item', to='schoolmeal.meal')),
            ],
        ),
    ]
