# Generated by Django 3.2.9 on 2021-11-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date', '-type']},
        ),
    ]
