# Generated by Django 3.2.9 on 2021-11-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmeal', '0002_alter_meal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealitem',
            name='allergy_codes',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
