# Generated by Django 3.2.9 on 2021-11-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmeal', '0003_alter_mealitem_allergy_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealitem',
            options={'ordering': ['id']},
        ),
    ]
