# Generated by Django 3.2.9 on 2021-11-07 09:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import timetable.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='수업 이름')),
                ('short_name', models.CharField(max_length=3, verbose_name='축약 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '1학년'), (2, '2학년'), (3, '3학년')], default=1, verbose_name='학년')),
                ('room', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='반')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='교무실')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='소속/역할')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='시정표 이름')),
                ('morning_meeting_start', models.TimeField(verbose_name='조회 시작 시간')),
                ('morning_meeting_end', models.TimeField(verbose_name='조회 종료 시간')),
                ('prepare_start', models.TimeField(verbose_name='수업 준비 시작 시간')),
                ('prepare_end', models.TimeField(verbose_name='수업 준비 종료 시간')),
                ('first_start', models.TimeField(verbose_name='1교시 시작 시간')),
                ('first_end', models.TimeField(verbose_name='1교시 종료 시간')),
                ('second_start', models.TimeField(verbose_name='2교시 시작 시간')),
                ('second_end', models.TimeField(verbose_name='2교시 종료 시간')),
                ('third_start', models.TimeField(verbose_name='3교시 시작 시간')),
                ('third_end', models.TimeField(verbose_name='3교시 종료 시간')),
                ('lunch_start', models.TimeField(verbose_name='중식 시작 시간')),
                ('lunch_end', models.TimeField(verbose_name='중식 종료 시간')),
                ('fourth_start', models.TimeField(verbose_name='4교시 시작 시간')),
                ('fourth_end', models.TimeField(verbose_name='4교시 종료 시간')),
                ('fifth_start', models.TimeField(verbose_name='5교시 시작 시간')),
                ('fifth_end', models.TimeField(verbose_name='5교시 종료 시간')),
                ('sisth_start', models.TimeField(verbose_name='6교시 시작 시간')),
                ('sisth_end', models.TimeField(verbose_name='6교시 종료 시간')),
                ('seventh_start', models.TimeField(verbose_name='7교시 시작 시간')),
                ('seventh_end', models.TimeField(verbose_name='7교시 종료 시간')),
                ('dinner_start', models.TimeField(verbose_name='석식 시작 시간')),
                ('dinner_end', models.TimeField(verbose_name='석식 종료 시간')),
            ],
        ),
        migrations.CreateModel(
            name='TempClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='변경 대상 날짜')),
                ('time', models.IntegerField(choices=[(1, '1교시'), (2, '2교시'), (3, '3교시'), (4, '4교시'), (5, '5교시'), (6, '6교시'), (7, '7교시')], default=1, verbose_name='교시')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.class', verbose_name='수업')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom', verbose_name='대상 학급')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='이름')),
                ('homeroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.classroom')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.office')),
                ('role', models.ManyToManyField(blank=True, to='timetable.Role')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(1, '1교시'), (2, '2교시'), (3, '3교시'), (4, '4교시'), (5, '5교시'), (6, '6교시'), (7, '7교시')], default=1, verbose_name='교시')),
                ('dayOfWeek', timetable.models.DayOfTheWeekField(choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (7, '일요일')], default=1, max_length=1, verbose_name='요일')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.class', verbose_name='수업')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom', verbose_name='대상 학급')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.teacher', verbose_name='담당 교사'),
        ),
    ]
