# Generated by Django 3.2.9 on 2021-11-07 10:03

from django.db import migrations, models
import timetable.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='dayOfWeek',
            field=timetable.models.DayOfTheWeekField(choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (7, '일요일')], default=1, verbose_name='요일'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='소속/역할'),
        ),
    ]
