# Generated by Django 3.2.9 on 2021-11-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20211107_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
