# Generated by Django 3.2.9 on 2021-11-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20211107_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempclass',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.class', verbose_name='수업'),
        ),
    ]
