# Generated by Django 3.2.9 on 2021-11-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_tempclass__class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableUseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(verbose_name='적용 시작 날짜')),
                ('enddate', models.DateField(verbose_name='적용 종료 날짜')),
                ('Timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable')),
            ],
        ),
    ]
