# Generated by Django 3.2.9 on 2021-11-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_timetableusedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetableusedate',
            old_name='Timetable',
            new_name='timetable',
        ),
    ]
