# Generated by Django 3.2.9 on 2021-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_timetableusedate_is_remote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableusedate',
            name='enddate',
            field=models.DateTimeField(verbose_name='적용 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='timetableusedate',
            name='startdate',
            field=models.DateTimeField(verbose_name='적용 시작 날짜'),
        ),
    ]
