# Generated by Django 3.2.9 on 2021-11-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_auto_20211107_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableusedate',
            name='enddate',
        ),
    ]
