# Generated by Django 3.2.9 on 2021-11-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_remove_timetableusedate_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='색상 코드'),
            preserve_default=False,
        ),
    ]
