# Generated by Django 3.2.9 on 2021-11-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0011_class_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='sisth_end',
            new_name='sixth_end',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='sisth_start',
            new_name='sixth_start',
        ),
    ]
