# Generated by Django 3.2.9 on 2021-11-10 10:56

from django.db import migrations
import timetable.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0012_auto_20211109_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempclass',
            name='dayOfWeek',
            field=timetable.models.DayOfTheWeekField(choices=[(1, '월요일'), (2, '화요일'), (3, '수요일'), (4, '목요일'), (5, '금요일'), (6, '토요일'), (7, '일요일')], default=1, verbose_name='요일'),
        ),
    ]
