# Generated by Django 3.2.9 on 2021-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0015_alter_timetableusedate_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableusedate',
            name='startdate',
            field=models.DateTimeField(verbose_name='적용 시작 날짜'),
        ),
    ]
