# Generated by Django 3.2.9 on 2021-11-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0017_alter_timetableusedate_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteurl',
            name='url',
            field=models.CharField(max_length=600, verbose_name='URL'),
        ),
    ]
