# Generated by Django 3.2.9 on 2021-11-15 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0018_alter_remoteurl_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteurl',
            old_name='url',
            new_name='pcurl',
        ),
    ]
