# Generated by Django 3.2.9 on 2021-11-15 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0020_alter_remoteurl_pcurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteurl',
            name='mobileurl',
            field=models.CharField(blank=True, max_length=600, verbose_name='MobileURL'),
        ),
    ]
