# Generated by Django 3.2.9 on 2021-11-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0022_alter_class_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='color',
            field=models.CharField(choices=[('#e8554f', 'Classic Red 1'), ('#c83a3a', 'Classic Red 2'), ('#a91a27', 'Classic Red 3'), ('#fcb345', 'Classic Orange 1'), ('#fc992e', 'Classic Orange 2'), ('#db7f28', 'Classic Orange 3'), ('#fce862', 'Classic Yellow 1'), ('#fccb4a', 'Classic Yellow 2'), ('#dcb031', 'Classic Yellow 3'), ('#8dde4f', 'Classic Green 1'), ('#70c336', 'Classic Green 2'), ('#55a628', 'Classic Green 3'), ('#77c5de', 'Classic Skyblue 1'), ('#5caac3', 'Classic Skyblue 2'), ('#408fa7', 'Classic Skyblue 3'), ('#688bf9', 'Classic Blue 1'), ('#4972db', 'Classic Blue 2'), ('#235bbe', 'Classic Blue 3'), ('#c77bfa', 'Classic Purple 1'), ('#aa61de', 'Classic Purple 2'), ('#8e49c0', 'Classic Purple 3'), ('#f77ebf', 'Classic Pink 1'), ('#d964a4', 'Classic Pink 2'), ('#bb4a8a', 'Classic Pink 3'), ('#909090', 'Classic Gray 1'), ('#777777', 'Classic Gray 2'), ('#5f5f5f', 'Classic Gray 3')], max_length=7, verbose_name='색상'),
        ),
    ]
