# Generated by Django 3.2.9 on 2021-12-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0023_alter_class_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasstingURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classtingurl', models.CharField(max_length=600, verbose_name='ClasstingURL')),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.class', verbose_name='수업')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.classroom', verbose_name='학급')),
            ],
        ),
    ]
