# Generated by Django 3.2.9 on 2021-12-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
