# Generated by Django 3.2.9 on 2022-01-04 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_articlephoto_articlevote_articlevoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlevoteitem',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='board.articlevote'),
        ),
    ]
