# Generated by Django 3.2.9 on 2022-01-06 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0008_auto_20220104_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlevoteitem',
            name='voted_users',
            field=models.ManyToManyField(blank=True, related_name='voted_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
